-- AlterTable
ALTER TABLE "DiaryEntry" ADD COLUMN "time" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "location" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "participants" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "DiaryEntry" ADD COLUMN "materials" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "procedures" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "decisions" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "learnings" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "difficulties" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "whatWorked" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "nextSteps" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "failedAttempts" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "possibleCauses" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "plannedAdjustments" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DiaryEntry" ADD COLUMN "newHypotheses" TEXT NOT NULL DEFAULT '';
